f:
  description: >-
    The optional f parameter indicates the output format which the server
    shall provide as part of the response document. It has preference over
    the HTTP Accept header. The default format is JSON.
  explode: false
  in: query
  name: f
  required: false
  schema:
    default: json
    enum:
      - json
      - html
    type: string
  style: form
sortby:
  description: >-
    The optional sortby parameter indicates the sort property and order on
    which the server shall present results in the response document using
    the convention `sortby=PROPERTY:X`, where `PROPERTY` is the sort
    property and `X` is the sort order (`A` is ascending, `D` is
    descending). Sorting by multiple properties is supported by providing a
    comma-separated list.
  explode: false
  in: query
  name: sortby
  required: false
  schema:
    type: string
  style: form
startindex:
  description: >-
    The optional startindex parameter indicates the index within the result
    set from which the server shall begin presenting results in the response
    document.  The first element has an index of 0 (default).
  explode: false
  in: query
  name: startindex
  required: false
  schema:
    default: 0
    minimum: 0
    type: integer
  style: form
